### ISSUE TITLE
Install only one binary

### ISSUE THREAD

**Issue by zkat** [licensezero/licensezero-cli#1]
Right now, the `l0` CLI installs a number of separate binaries for the different involved commands. I think this has 2 issues I'm running into:

1. It's not obvious that's an `l`. People are used to `l0` reading as `10`, and that was, frankly, my first thought.

2. It makes it more laborious to use through [`npx`](https://npm.im/npx), which might make it much easier to people to just pick up the tool and start using it right away. In order to use it with this tool, you'd need to do `$ npx -p licensezero -- l0-license ....`.

#### Proposal

I suggest moving all of these binaries under a single command, simply called `licensezero`, and using [`yargs`](https://npm.im/yargs) or similar to make it work using subcommands. I see that this might require a bit of refactoring, but I'm willing to help, if you'd take the patch.

Also, why it doesn't solve the first item above, it might be of interest of you to know that https://npm.im/l0 isn't taken, so you could pick it up and use it for dual-publishing. That way, you could do `$ npx l0 create-license ...` and it would Just Work™.

Let me know how all this sounds and any constraints you have! I'm happy to submit a patch with this refactor if you'd rather someone else do it. 👍

**Comment by kemitchell** [comment]
I believe I've got this in bd29bd539b173a59666ed4d173db98752750c5ba
